### ISSUE TITLE
Feature #1: Users can create a transaction.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can create a transaction for the deposit and withdraw money.
Also, they can store their transaction records in more detail.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking plus icon on the bottom will lead to the deposit and withdrawal form.
Able to add the date, category, amount, and short description for their transaction data.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/68725614/119562970-d2213f80-bd5b-11eb-8dd2-fd1dc28cc841.png)
![image](https://user-images.githubusercontent.com/68725614/119902692-793cdd00-befc-11eb-88dc-aa0d7f89296b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create a database name fetchInCleverConsumption.
- [x] Update `schema.sql` to make a table to store the data.
- [x] Update `data.sql` to make a table to store the data.

### ☁️ Server

- [x] Create `server/index.js` to store transaction data that handle the POST request, including an auto-generated Id property.
- [x] Add Put method to update the date, category, amount, and description.
- [x] Test it in the terminal.
- [x] Handle all errors and response status code to the client.

### ⚡ Client

- [x] Create a component for each modal form tab on the add transaction page.
- [x] Update component to match the result of what I selected.

### 🧑‍⚕️ Clean Up

- [x] Create an add transaction page like my wireframe that contains a header, form, and footer.
- [x] Add form event listeners on the Save button.
- [x] Add click event listener that responds to deposit and withdrawal buttons.
- [x] Add date input and select element for the date and category.
- [x] Ensure to check saved transaction stores in the local storage.
- [x] Ensure to check the Cancel button make go back to the previous page.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs, commented out code or CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on mobile screens.
