### ISSUE TITLE
Feature #2: User can see daily expenditure history.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their expenditure history in the daily tab.
Furthermore, they can see their total amount of income and expenses, also their balance amount.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking the daily tab on the nav bar will lead to the daily expenditure history page.
If the user created their transaction in the past, the saved data is rendered as a list.
At this point, the more recent date transaction is aligned at the higher of the page.
The income, expenses, and total contain the total amount of income, expenses, and the balance.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/68725614/120739367-3f447b80-c4a6-11eb-9820-61adc4a11e75.png)
![image](https://user-images.githubusercontent.com/68725614/120949043-6e522b80-c6f8-11eb-9195-33aadc6cdce6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a GET request to get the transaction information in the `server/index.js`.

### ⚡ Client

- [x] Create a component to render the list for the transaction history onto the page.
- [x] Create a component to calculate the transaction history for income, expenses, and total amount.
- [x] Update component to get the recent income, expenses, and total amount.

### 🧑‍⚕️ Clean Up

- [x] Create a main page like my wireframe that contains a header, navbar, and footer.
- [x] Add a route path in the `client/App.jsx` for the plus icon anchor tag that responds to show adding transaction form page.
- [x] Use the map method to render the list element for the transaction history on the page.
- [x] Make sure that recent date transaction is aligned at the higher instead of recent transaction history on the Daily page.
- [x] Add a route path in the `client/App.jsx` for the Daily tab that responds to show daily expenditure history.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the 
- [x] Check all code for proper formatting and indentation.
- [x] Remove all console logs, commented out code or CSS properties that do not affect.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on mobile screens.
